import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const common = {
	banner: {
		js: banner,
	},
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	loader: {
		".css": "empty",
		".less": "empty",
	},
	define: {
		"process.env.NODE_ENV": prod ? '"production"' : '"development"',
	},
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minify: prod,
};

const mainContext = await esbuild.context({
	...common,
	entryPoints: ["src/main.ts"],
	format: "cjs",
	outfile: "main.js",
});

// Ketcher is kept in a separate browser bundle so the main Obsidian plugin can
// continue to load on mobile and before the editor is opened. The runtime is
// loaded lazily by chem/ketcher-host.ts when a chemistry modal is opened.
const ketcherContext = await esbuild.context({
	entryPoints: ["src/chem/ketcher-runtime.tsx"],
	bundle: true,
	format: "iife",
	platform: "browser",
	target: "es2018",
	outfile: "ketcher.js",
	logLevel: "info",
	loader: {
		".css": "css",
		".less": "css",
	},
	define: {
		"process.env.NODE_ENV": prod ? '"production"' : '"development"',
		process: JSON.stringify({ env: { NODE_ENV: prod ? "production" : "development" } }),
		global: "globalThis",
	},
	minify: prod,
});

if (prod) {
	await mainContext.rebuild();
	await ketcherContext.rebuild();
	process.exit(0);
} else {
	await Promise.all([mainContext.watch(), ketcherContext.watch()]);
}
