import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const common = {
	banner: {
		js: banner,
	},
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	loader: {
		".css": "empty",
		".less": "empty",
	},
	define: {
		"process.env.NODE_ENV": prod ? '"production"' : '"development"',
	},
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minify: prod,
};

const mainContext = await esbuild.context({
	...common,
	entryPoints: ["src/main.ts"],
	format: "cjs",
	outfile: "main.js",
});

const ketcherContext = await esbuild.context({
	...common,
	entryPoints: ["src/chem/ketcher-runtime.ts"],
	external: [],
	format: "iife",
	globalName: "ScholariumKetcherRuntime",
	outfile: "ketcher-runtime.js",
});

if (prod) {
	await mainContext.rebuild();
	await ketcherContext.rebuild();
	process.exit(0);
} else {
	await mainContext.watch();
	await ketcherContext.watch();
}
