// 精选 emoji 数据，用于科研工具卡片的"图标"字段。
// 每个 emoji 至少包含一组中英关键词，便于搜索过滤。
// 体积刻意保持较小（数百个），覆盖学术、办公、科研、自然、物品等常见场景。

export interface EmojiEntry {
    char: string;
    /** 搜索关键词（小写、可中英混合）。匹配采用 `includes` 模糊匹配。 */
    keywords: string[];
}

export interface EmojiGroup {
    name: string;
    items: EmojiEntry[];
}

export const EMOJI_GROUPS: EmojiGroup[] = [
    {
        name: '科研与学术',
        items: [
            { char: '🔬', keywords: ['microscope', '显微镜', '科研', '实验', 'lab'] },
            { char: '🧬', keywords: ['dna', '基因', '生物', '遗传', 'biology'] },
            { char: '🧪', keywords: ['test tube', '试管', '化学', '实验', 'chem'] },
            { char: '⚗️', keywords: ['alembic', '蒸馏', '化学', '炼金'] },
            { char: '🧫', keywords: ['petri', '培养皿', '细胞', '微生物'] },
            { char: '🧮', keywords: ['abacus', '算盘', '计算', 'count'] },
            { char: '🔭', keywords: ['telescope', '望远镜', '天文', '观测'] },
            { char: '🛰️', keywords: ['satellite', '卫星', '航天', '通信'] },
            { char: '🧲', keywords: ['magnet', '磁铁', '物理'] },
            { char: '⚛️', keywords: ['atom', '原子', '物理', '量子'] },
            { char: '🪐', keywords: ['planet', '土星', '行星', '天文'] },
            { char: '🌌', keywords: ['galaxy', '银河', '宇宙', '星空'] },
            { char: '📐', keywords: ['triangle ruler', '三角板', '几何', '数学'] },
            { char: '📏', keywords: ['ruler', '直尺', '尺寸', '测量'] },
            { char: '🧠', keywords: ['brain', '大脑', '思考', '神经'] },
            { char: '🩺', keywords: ['stethoscope', '听诊器', '医学', '医生'] },
            { char: '💉', keywords: ['syringe', '注射', '疫苗', '医学'] },
            { char: '💊', keywords: ['pill', '药丸', '医药', '医学'] },
            { char: '🧴', keywords: ['lotion', '试剂', '瓶子'] },
            { char: '🧰', keywords: ['toolbox', '工具箱', 'tool'] },
            { char: '⚙️', keywords: ['gear', '齿轮', '设置', '机制'] },
            { char: '🔧', keywords: ['wrench', '扳手', '工具', '配置'] },
            { char: '🛠️', keywords: ['tools', '工具', '配置', '修理'] },
            { char: '🔋', keywords: ['battery', '电池', '能源'] },
            { char: '🔌', keywords: ['plug', '插头', '电源'] },
            { char: '🧭', keywords: ['compass', '指南针', '方向', '导航'] },
            { char: '🗺️', keywords: ['map', '地图', '导航', '世界'] },
            { char: '🌍', keywords: ['earth', '地球', '欧非', '环球'] },
            { char: '🌎', keywords: ['earth', '地球', '美洲'] },
            { char: '🌏', keywords: ['earth', '地球', '亚洲'] },
        ],
    },
    {
        name: '办公与文档',
        items: [
            { char: '📚', keywords: ['books', '书', '文献', '阅读'] },
            { char: '📖', keywords: ['open book', '打开的书', '阅读', '学习'] },
            { char: '📕', keywords: ['red book', '红书', '书籍'] },
            { char: '📗', keywords: ['green book', '绿书', '书籍'] },
            { char: '📘', keywords: ['blue book', '蓝书', '书籍'] },
            { char: '📙', keywords: ['orange book', '橙书', '书籍'] },
            { char: '📓', keywords: ['notebook', '笔记本', '记录'] },
            { char: '📔', keywords: ['decorated notebook', '日记本'] },
            { char: '📒', keywords: ['ledger', '账本', '笔记'] },
            { char: '📝', keywords: ['memo', '笔记', '写作', '编辑'] },
            { char: '✏️', keywords: ['pencil', '铅笔', '编辑'] },
            { char: '✒️', keywords: ['fountain pen', '钢笔', '签名'] },
            { char: '🖊️', keywords: ['pen', '签字笔'] },
            { char: '🖋️', keywords: ['fountain pen', '钢笔'] },
            { char: '🖌️', keywords: ['paintbrush', '画笔'] },
            { char: '🖍️', keywords: ['crayon', '蜡笔'] },
            { char: '📄', keywords: ['document', '文档', 'paper'] },
            { char: '📃', keywords: ['page', '文档', '纸张'] },
            { char: '📜', keywords: ['scroll', '卷轴', '文献', '协议'] },
            { char: '📋', keywords: ['clipboard', '剪贴板', '清单'] },
            { char: '📑', keywords: ['bookmark tabs', '书签', '索引'] },
            { char: '📰', keywords: ['newspaper', '报纸', '新闻'] },
            { char: '🗞️', keywords: ['rolled newspaper', '报刊'] },
            { char: '📅', keywords: ['calendar', '日历'] },
            { char: '📆', keywords: ['tear off calendar', '日历', '日期'] },
            { char: '🗓️', keywords: ['spiral calendar', '日历'] },
            { char: '📇', keywords: ['card index', '卡片索引', '名片'] },
            { char: '🗂️', keywords: ['card index dividers', '卡片', '分类'] },
            { char: '📁', keywords: ['folder', '文件夹'] },
            { char: '📂', keywords: ['open folder', '打开文件夹'] },
            { char: '🗃️', keywords: ['card file box', '档案盒'] },
            { char: '🗄️', keywords: ['file cabinet', '文件柜'] },
            { char: '📊', keywords: ['bar chart', '柱状图', '数据'] },
            { char: '📈', keywords: ['chart up', '上升', '增长', '趋势'] },
            { char: '📉', keywords: ['chart down', '下降', '下跌'] },
            { char: '📌', keywords: ['pushpin', '图钉', '固定'] },
            { char: '📍', keywords: ['round pin', '位置', '标记'] },
            { char: '🔖', keywords: ['bookmark', '书签'] },
            { char: '🏷️', keywords: ['label', '标签', 'tag'] },
            { char: '🗒️', keywords: ['spiral notepad', '便签'] },
            { char: '✂️', keywords: ['scissors', '剪刀'] },
            { char: '📎', keywords: ['paperclip', '回形针', '附件'] },
            { char: '🖇️', keywords: ['linked paperclips', '回形针', '附件'] },
            { char: '📐', keywords: ['triangular ruler', '三角板'] },
            { char: '📏', keywords: ['ruler', '直尺'] },
            { char: '🧷', keywords: ['safety pin', '别针'] },
            { char: '📦', keywords: ['package', '包裹', '盒子'] },
            { char: '📤', keywords: ['outbox', '发件箱'] },
            { char: '📥', keywords: ['inbox', '收件箱'] },
            { char: '📨', keywords: ['incoming envelope', '邮件'] },
            { char: '📧', keywords: ['email', '电邮'] },
            { char: '📮', keywords: ['postbox', '邮筒'] },
        ],
    },
    {
        name: '电脑与互联网',
        items: [
            { char: '💻', keywords: ['laptop', '笔记本电脑', '计算机'] },
            { char: '🖥️', keywords: ['desktop computer', '台式机'] },
            { char: '🖨️', keywords: ['printer', '打印机'] },
            { char: '⌨️', keywords: ['keyboard', '键盘'] },
            { char: '🖱️', keywords: ['mouse', '鼠标'] },
            { char: '🖲️', keywords: ['trackball', '轨迹球'] },
            { char: '💾', keywords: ['floppy disk', '保存', '软盘'] },
            { char: '💿', keywords: ['cd', '光盘'] },
            { char: '📀', keywords: ['dvd', '光盘'] },
            { char: '💽', keywords: ['minidisk', '光盘'] },
            { char: '📱', keywords: ['mobile phone', '手机'] },
            { char: '📲', keywords: ['mobile call', '来电'] },
            { char: '☎️', keywords: ['telephone', '电话'] },
            { char: '📞', keywords: ['phone', '电话'] },
            { char: '📟', keywords: ['pager', '寻呼机'] },
            { char: '📠', keywords: ['fax', '传真'] },
            { char: '📡', keywords: ['satellite antenna', '卫星', '天线', '信号'] },
            { char: '🌐', keywords: ['globe meridians', '互联网', '全球', 'web'] },
            { char: '🔗', keywords: ['link', '链接', 'url'] },
            { char: '🔍', keywords: ['magnifying glass', '搜索', '放大镜', 'search'] },
            { char: '🔎', keywords: ['magnifying glass right', '搜索', '放大镜'] },
            { char: '🔒', keywords: ['locked', '锁', '加密'] },
            { char: '🔓', keywords: ['unlocked', '解锁'] },
            { char: '🔐', keywords: ['locked with key', '加密', '密钥'] },
            { char: '🔑', keywords: ['key', '钥匙'] },
            { char: '🗝️', keywords: ['old key', '钥匙'] },
            { char: '🆔', keywords: ['id', '账号', '身份'] },
            { char: '🔔', keywords: ['bell', '通知', '提醒'] },
            { char: '🔕', keywords: ['bell off', '静音'] },
        ],
    },
    {
        name: '符号与提示',
        items: [
            { char: '⭐', keywords: ['star', '星标', '收藏'] },
            { char: '🌟', keywords: ['glowing star', '星星'] },
            { char: '✨', keywords: ['sparkles', '闪光', '新'] },
            { char: '💡', keywords: ['light bulb', '灵感', '点子', 'idea'] },
            { char: '🔥', keywords: ['fire', '火', '热门'] },
            { char: '⚡', keywords: ['high voltage', '闪电', '快'] },
            { char: '💥', keywords: ['collision', '冲击', '爆炸'] },
            { char: '💫', keywords: ['dizzy', '晕', '星'] },
            { char: '🌈', keywords: ['rainbow', '彩虹'] },
            { char: '☀️', keywords: ['sun', '太阳'] },
            { char: '🌙', keywords: ['moon', '月亮'] },
            { char: '❄️', keywords: ['snowflake', '雪花'] },
            { char: '☁️', keywords: ['cloud', '云'] },
            { char: '☂️', keywords: ['umbrella', '伞'] },
            { char: '🌊', keywords: ['wave', '海浪'] },
            { char: '✅', keywords: ['check', '勾', '完成'] },
            { char: '☑️', keywords: ['ballot check', '勾选'] },
            { char: '❎', keywords: ['cross mark box', '叉', '错误'] },
            { char: '❌', keywords: ['cross mark', '错', 'x'] },
            { char: '⚠️', keywords: ['warning', '警告', '注意'] },
            { char: '❗', keywords: ['exclamation', '感叹', '重要'] },
            { char: '❓', keywords: ['question', '问题', '疑问'] },
            { char: '‼️', keywords: ['double exclamation', '重要'] },
            { char: '⁉️', keywords: ['exclamation question', '惊问'] },
            { char: '🆕', keywords: ['new', '新'] },
            { char: '🆗', keywords: ['ok'] },
            { char: '🆒', keywords: ['cool', '酷'] },
            { char: '🆓', keywords: ['free', '免费'] },
            { char: '🔝', keywords: ['top', '顶部', '最高'] },
            { char: '➕', keywords: ['plus', '加'] },
            { char: '➖', keywords: ['minus', '减'] },
            { char: '✖️', keywords: ['multiply', '乘', '叉'] },
            { char: '➗', keywords: ['divide', '除'] },
            { char: '♻️', keywords: ['recycle', '回收', '循环'] },
            { char: '✳️', keywords: ['eight spoked asterisk', '星号'] },
            { char: '🔢', keywords: ['1234', '数字'] },
            { char: '🔠', keywords: ['uppercase', '大写'] },
            { char: '🔡', keywords: ['lowercase', '小写'] },
            { char: '🔣', keywords: ['symbols', '符号'] },
            { char: '🔤', keywords: ['letters', 'abc', '字母'] },
            { char: '💯', keywords: ['hundred', '100', '满分'] },
        ],
    },
    {
        name: '人与活动',
        items: [
            { char: '👨‍🔬', keywords: ['scientist man', '男科学家'] },
            { char: '👩‍🔬', keywords: ['scientist woman', '女科学家'] },
            { char: '🧑‍🔬', keywords: ['scientist', '科学家'] },
            { char: '👨‍🏫', keywords: ['teacher man', '男老师'] },
            { char: '👩‍🏫', keywords: ['teacher woman', '女老师'] },
            { char: '🧑‍🏫', keywords: ['teacher', '老师', '教师'] },
            { char: '👨‍💻', keywords: ['developer man', '男程序员'] },
            { char: '👩‍💻', keywords: ['developer woman', '女程序员'] },
            { char: '🧑‍💻', keywords: ['developer', '程序员', '开发'] },
            { char: '🎓', keywords: ['mortar board', '学位帽', '毕业'] },
            { char: '🏆', keywords: ['trophy', '奖杯', '冠军'] },
            { char: '🥇', keywords: ['gold medal', '金牌'] },
            { char: '🥈', keywords: ['silver medal', '银牌'] },
            { char: '🥉', keywords: ['bronze medal', '铜牌'] },
            { char: '🎯', keywords: ['target', '目标', '靶'] },
            { char: '🚀', keywords: ['rocket', '火箭', '发射'] },
            { char: '🎉', keywords: ['party', '庆祝'] },
            { char: '🎊', keywords: ['confetti', '彩花'] },
            { char: '👍', keywords: ['thumbs up', '点赞'] },
            { char: '👎', keywords: ['thumbs down', '差评'] },
            { char: '👏', keywords: ['clap', '鼓掌'] },
            { char: '🙌', keywords: ['raising hands', '欢呼'] },
            { char: '💪', keywords: ['flex', '加油', '肌肉'] },
            { char: '🤝', keywords: ['handshake', '握手', '合作'] },
            { char: '🙏', keywords: ['pray', '感谢', '祈祷'] },
            { char: '👀', keywords: ['eyes', '眼睛', '关注'] },
            { char: '🫶', keywords: ['heart hands', '比心'] },
        ],
    },
    {
        name: '自然与动植物',
        items: [
            { char: '🌱', keywords: ['seedling', '幼苗', '成长'] },
            { char: '🌿', keywords: ['herb', '草本', '叶子'] },
            { char: '🍀', keywords: ['four leaf clover', '四叶草', '幸运'] },
            { char: '🌳', keywords: ['tree', '树'] },
            { char: '🌲', keywords: ['evergreen', '松树'] },
            { char: '🌴', keywords: ['palm tree', '棕榈'] },
            { char: '🌵', keywords: ['cactus', '仙人掌'] },
            { char: '🌷', keywords: ['tulip', '郁金香'] },
            { char: '🌸', keywords: ['cherry blossom', '樱花'] },
            { char: '🌹', keywords: ['rose', '玫瑰'] },
            { char: '🌺', keywords: ['hibiscus', '木槿'] },
            { char: '🌻', keywords: ['sunflower', '向日葵'] },
            { char: '🌼', keywords: ['daisy', '雏菊'] },
            { char: '🦋', keywords: ['butterfly', '蝴蝶'] },
            { char: '🐝', keywords: ['bee', '蜜蜂'] },
            { char: '🐞', keywords: ['ladybug', '瓢虫', 'bug'] },
            { char: '🐢', keywords: ['turtle', '乌龟'] },
            { char: '🐬', keywords: ['dolphin', '海豚'] },
            { char: '🐳', keywords: ['whale', '鲸鱼'] },
            { char: '🦒', keywords: ['giraffe', '长颈鹿'] },
            { char: '🦊', keywords: ['fox', '狐狸'] },
            { char: '🦉', keywords: ['owl', '猫头鹰'] },
        ],
    },
    {
        name: '食物与饮品',
        items: [
            { char: '☕', keywords: ['coffee', '咖啡'] },
            { char: '🍵', keywords: ['tea', '茶'] },
            { char: '🧋', keywords: ['bubble tea', '奶茶'] },
            { char: '🥤', keywords: ['cup straw', '饮料'] },
            { char: '🍺', keywords: ['beer', '啤酒'] },
            { char: '🍷', keywords: ['wine', '红酒'] },
            { char: '🥛', keywords: ['milk', '牛奶'] },
            { char: '🍎', keywords: ['apple', '苹果'] },
            { char: '🍊', keywords: ['orange', '橘子'] },
            { char: '🍋', keywords: ['lemon', '柠檬'] },
            { char: '🍇', keywords: ['grapes', '葡萄'] },
            { char: '🍓', keywords: ['strawberry', '草莓'] },
            { char: '🍔', keywords: ['hamburger', '汉堡'] },
            { char: '🍕', keywords: ['pizza', '披萨'] },
            { char: '🍜', keywords: ['noodles', '面条'] },
            { char: '🍣', keywords: ['sushi', '寿司'] },
            { char: '🍰', keywords: ['cake', '蛋糕'] },
            { char: '🍪', keywords: ['cookie', '饼干'] },
            { char: '🍫', keywords: ['chocolate', '巧克力'] },
        ],
    },
    {
        name: '其他常用',
        items: [
            { char: '🏠', keywords: ['home', '家', '主页'] },
            { char: '🏢', keywords: ['office building', '办公楼'] },
            { char: '🏛️', keywords: ['classical building', '机构', '学院'] },
            { char: '🏫', keywords: ['school', '学校'] },
            { char: '🏥', keywords: ['hospital', '医院'] },
            { char: '🛒', keywords: ['shopping cart', '购物车'] },
            { char: '🎁', keywords: ['gift', '礼物'] },
            { char: '🎵', keywords: ['music note', '音乐'] },
            { char: '🎶', keywords: ['music notes', '音乐'] },
            { char: '🎬', keywords: ['clapper board', '电影'] },
            { char: '🎮', keywords: ['game', '游戏'] },
            { char: '🎲', keywords: ['die', '骰子', '随机'] },
            { char: '🧩', keywords: ['puzzle', '拼图'] },
            { char: '🪄', keywords: ['magic wand', '魔法棒'] },
            { char: '🎨', keywords: ['art palette', '调色', '设计'] },
            { char: '📸', keywords: ['camera flash', '相机', '拍照'] },
            { char: '📷', keywords: ['camera', '相机'] },
            { char: '🎥', keywords: ['movie camera', '摄像机'] },
            { char: '🎤', keywords: ['microphone', '麦克风'] },
            { char: '🎧', keywords: ['headphone', '耳机'] },
            { char: '🔊', keywords: ['loud sound', '声音'] },
            { char: '🔇', keywords: ['muted', '静音'] },
        ],
    },
];

/**
 * 扁平所有 emoji，便于搜索时不需要重复展开。
 */
export const ALL_EMOJIS: EmojiEntry[] = EMOJI_GROUPS.flatMap(group => group.items);

/**
 * 在所有 emoji 中按关键词模糊搜索。空查询返回空数组（调用方应用分组数据）。
 */
export function searchEmojis(query: string): EmojiEntry[] {
    const q = query.trim().toLowerCase();
    if (!q) return [];
    const seen = new Set<string>();
    const out: EmojiEntry[] = [];
    for (const e of ALL_EMOJIS) {
        if (seen.has(e.char)) continue;
        if (e.char === q || e.keywords.some(k => k.toLowerCase().includes(q))) {
            seen.add(e.char);
            out.push(e);
        }
    }
    return out;
}
